apiVersion: v1
kind: Pod
metadata:
  name: temp
  labels:
    creation_method: manual
    env: dev
spec:
  containers:
    - image: mstepan/reactive-wiki:1.0.0-SNAPSHOT
      name: temp
      ports:
        - containerPort: 8080
          protocol: TCP
