apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: wiki-replica-set
  labels:
    app: wiki-replica-set
    creation_method: manual
    data_center: dc6
    tribe: dss
    env: dev

spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactive-wiki

  template:
    metadata:
      name: reactive-wiki
      labels:
        app: reactive-wiki
        creation_method: manual
        data_center: dc6
        tribe: dss
        env: dev
    spec:
      containers:
        - image: mstepan/reactive-wiki:1.0.0-SNAPSHOT
          name: reactive-wiki
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.5"
            limits:
              memory: "512Mi"
              cpu: "0.5"
