apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-deployment
  labels:
    app: wiki-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactive-wiki
  template:
    metadata:
      name: reactive-wiki
      labels:
        app: reactive-wiki
        creation_method: manual
        data_center: dc6
        tribe: dss
        env: dev
    spec:
      containers:
        - image: mstepan/reactive-wiki:1.0.0-SNAPSHOT
          name: reactive-wiki
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.3"
            limits:
              memory: "256Mi"
              cpu: "0.3"
